# If you come from basdh you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH

# Nexus setup
source ~/.mavenrc

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git docker fzf volta sdk gh git-auto-fetch golang kubectx thefuck tmux yarn)
source $ZSH/oh-my-zsh.sh

### SETTINGS ###
# You may need to manually set your language environment
export LANG=da_DK.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
fi

# Custome aliases
alias icloud="cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs"
alias savemyday="cd ~/Code/save-my-day/"
### SETTINGS ###
# You may need to manually set your language environment
export LANG=da_DK.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
fi

# Custome aliases
alias icloud="cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs"
alias savemyday="cd ~/Code/save-my-day/"
### TOOLS ###
# Volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# SSH Agent
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

# Tmux
alias tat="tmux attach -t"
alias tnn="tmux new -s"

# Git
fd() {
  preview="git diff $@ --color=always -- {-1}"
  git diff $@ --name-only | fzf -m --ansi --preview $preview
}

# Admin by request
export HOMEBREW_CASK_OPTS="--appdir=~/Applications"

# Wezterm
export PATH="$PATH:/Applications/WezTerm.app/Contents/MacOS"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

### LANGUAGES ###
# Go
export GO111MODULE=auto
export GOPATH=$HOME/go:$HOME/Code
export GOPRIVATE=github.com/UrgeToday/*
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH

# Python
alias python="/opt/homebrew/bin/python3"
alias pip3="/opt/homebrew/bin/pip"
export PYTHONPATH="$HOME/scripts:$PYTHONPATH"

# Ruby
if [ -d "/opt/homebrew/opt/ruby/bin" ]; then
  export PATH=/opt/homebrew/opt/ruby/bin:$PATH
  export PATH=`gem environment gemdir`/bin:$PATH
fi
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

