# If you come from basdh you might have to change your $PATH.
export PATH=/opt/homebrew/bin:$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="spaceship"
plugins=(git docker fzf volta sdk gh golang kubectx thefuck yarn)
source $ZSH/oh-my-zsh.sh

### SETTINGS ###
# You may need to manually set your language environment
export LANG=da_DK.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
fi

# Custome aliases
alias icloud="cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs"

### SETTINGS ###
# You may need to manually set your language environment
export LANG=da_DK.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
fi

### TOOLS ###

# SSH agent: use 1Password's if this machine has it, otherwise leave the
# default agent alone.
OP_SSH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
[ -S "$OP_SSH_SOCK" ] && export SSH_AUTH_SOCK="$OP_SSH_SOCK"
unset OP_SSH_SOCK

# NVM
export NVM_DIR="$HOME/.nvm"
for _brew in "${HOMEBREW_PREFIX:-}" /opt/homebrew /usr/local; do
  [ -n "$_brew" ] && [ -s "$_brew/opt/nvm/nvm.sh" ] || continue
  \. "$_brew/opt/nvm/nvm.sh"
  [ -s "$_brew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$_brew/opt/nvm/etc/bash_completion.d/nvm"
  break
done
unset _brew

# Tmux
alias tat="tmux attach -t"
alias tnn="tmux new -s"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

### LANGUAGES ###
# Go
export GO111MODULE=auto
export GOPATH=$HOME/go:$HOME/Code
export GOPRIVATE=github.com/UrgeToday/*
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH

# Python
alias python="/opt/homebrew/bin/python3"
alias pip3="/opt/homebrew/bin/pip"
export PYTHONPATH="$HOME/scripts:$PYTHONPATH"

# Ruby
if [ -d "/opt/homebrew/opt/ruby/bin" ]; then
  export PATH=/opt/homebrew/opt/ruby/bin:$PATH
  export PATH=`gem environment gemdir`/bin:$PATH
fi
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
[ -d "$HOME/.docker/completions" ] && fpath=("$HOME/.docker/completions" $fpath)
autoload -Uz compinit
compinit

# End of Docker CLI completions
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if command -v nvm >/dev/null; then
  autoload -U add-zsh-hook
  load-nvmrc() {
    local nvmrc_path="$(nvm_find_nvmrc)"
    if [ -n "$nvmrc_path" ]; then
      local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
      if [ "$nvmrc_node_version" = "N/A" ]; then
        nvm install
      elif [ "$nvmrc_node_version" != "$(nvm version)" ]; then
        nvm use
      fi
    fi
  }
  add-zsh-hook chpwd load-nvmrc
  load-nvmrc
fi

# Per-machine and work-specific settings. Not versioned. Sourced last so it
# can override anything above.
[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"
