#!/bin/bash

set -e

command -v brew >/dev/null 2>&1 || {
  echo >&2 "Installing Homebrew Now"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  # Put brew on PATH now, and persist it. Apple Silicon and Intel differ.
  for _brew in /opt/homebrew/bin/brew /usr/local/bin/brew; do
    [ -x "$_brew" ] || continue
    eval "$("$_brew" shellenv)"
    printf 'eval "$(%s shellenv)"\n' "$_brew" >>"$HOME/.zprofile"
    break
  done
  unset _brew
}

brew install coreutils # Install GNU core utilities (those that come with OS X are outdated)
brew install findutils # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed

binaries=(
  bat
  curl
  defaultbrowser
  fd
  fsouza/prettierd/prettierd
  fzf
  gcc
  go
  golang-migrate
  grep
  lazygit
  lua
  lua-language-server
  luarocks
  make
  maven
  mas # For installing from App Store
  neovim
  nginx
  openssl
  rename
  ripgrep
  selecta
  sdkman-cli
  sqlc
  the_silver_searcher
  thefuck
  tmux
  tpm
  tree
  vim
  wget
  zsh
)

for i in "${binaries[@]}"; do
  brew install "$i"
done

brew tap sdkman/tap
