#!/bin/bash

brew tap caskroom/cask
brew tap caskroom/versions

# Xcode, Magnet, 1Password, Pocket, Slack, Trello, Whatsapp
appStore=(
  497799835
  441258766
  1333542190
  568494494
  803453959
  1176895641
  1278508951
  1147396723
)

for i in "${appStore[@]}"
do
  mas install "$i"
done

apps=(
  caffeine
  dropbox
  google-chrome
  ngrok
  iterm2
  java
  postman
  docker
  skype
  sourcetree
  sublime-text
  vlc
)

for i in "${appStore[@]}"
do
  brew cask install "$i"
done

# Install docker
open https://www.docker.com/products/docker\#/mac

# Install Jetbrains Toolbox
open https://www.jetbrains.com/toolbox/app/

# cleanup
brew cleanup --force
rm -f -r /Library/Caches/Homebrew/*
