#!/bin/bash

brew tap caskroom/cask
brew tap caskroom/versions

apps=(
  1password
  caffeine
  dropbox
  google-chrome
  ngrok
  iterm2
  intellij-idea
  java
  postman
  skype
  sublime-text
  vlc
)

brew cask install ${apps[@]}
brew cleanup
