#!/bin/zsh
#
set -e
ROOT=${1:-~}

function main {
    install_applications
    setup_dotfiles
}

function install_applications {
    ./Brewfile
    ./Caskfile
    ./AppStore
    ./NPM
}

function setup_dotfiles {
  test -d "$ROOT/.config" || mkdir -p "$ROOT/.config"

  settings
  zsh
  oh_my_zsh
}

function zsh {
  if ! type "/usr/local/bin/zsh" > /dev/null; then
    brew install zsh
  fi
  chsh -s /usr/local/bin/zsh $USER
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
}

function oh_my_zsh {
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

function settings {
  DOTFILES="dotfiles"
  symlink "$DOTFILES/ag/agignore" ".agignore"
  symlink "$DOTFILES/git/gitconfig" ".gitconfig"
  symlink "$DOTFILES/git/gitignore_global" ".gitignore_global"
  symlink "$DOTFILES/vim/vimrc" ".vimrc"
  symlink "$DOTFILES/vim/" ".vim"
  symlink "$DOTFILES/nvim/" ".config/nvim"
  symlink "$DOTFILES/zsh/zshrc" ".zshrc"
  symlink "$DOTFILES/zsh/profile" ".profile"
  symlink "$DOTFILES/settings/idea" ".idea"
}

function symlink() {
  TARGET=$ROOT/${2:-.$1}
  echo $TARGET
  if [[ -e $TARGET ]]; then
    rm -rf $TARGET
  fi
  ln -nfs $ROOT/$1 $TARGET
}

main
