#!/bin/zsh
#
set -e
ROOT=${1:-~}

function main {
  test -d "$ROOT/.config" || mkdir -p "$ROOT/.config"
  install_packages
  install_rvm
  install_nvm
  setup_vim
  setup_zsh
}

function install_rvm {
  if ! type "rvm"; then
    gpg --keyserver hkp://b4ckbone.de --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    \curl -sSL https://get.rvm.io | bash -s stable --ruby
  fi
}

function install_nvm {
  if ! type "nvm"; then
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash
  fi
}

function setup_zsh {
  if ! type "/usr/local/bin/zsh" > /dev/null; then
    brew install zsh
  fi
  chsh -s /usr/local/bin/zsh $USER
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
}

function setup_vim {
  VUNDLE_DIR="vim/bundle/Vundle.vim"
  if ! -d "$VUNDLE_DIR"; then
    git clone https://github.com/VundleVim/Vundle.vim.git $VUNDLE_DIR
    vim +PluginInstall +qall
  fi
}

function install_packages {
  DOTFILES="dotfiles"
  symlink "$DOTFILES/git/gitconfig" ".gitconfig"
  symlink "$DOTFILES/git/gitignore_global" ".gitignore_global"
  symlink "$DOTFILES/vim/vimrc" ".vimrc"
  symlink "$DOTFILES/vim/" ".vim"
  symlink "$DOTFILES/zsh/oh-my-zsh/" ".oh-my-zsh"
  symlink "$DOTFILES/zsh/zshrc" ".zshrc"
  symlink "$DOTFILES/zsh/profile" ".profile"
}

function symlink() {
  TARGET=$ROOT/${2:-.$1}
  echo $TARGET
  if [[ -e $TARGET ]]; then
    rm -rf $TARGET
  fi
  ln -nfs $ROOT/$1 $TARGET
}

main
