#!/bin/bash

function install_applications {
    ./InstallSteps/Brewfile
    ./InstallSteps/Caskfile
    ./InstallSteps/AppStore
    ./InstallSteps/NPM
    ./InstallSteps/Shell
}

install_applications
