#!/bin/zsh

command -v nvm >/dev/null 2>&1 || { echo >&2 "Installing NVM Now"; \
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash }

packages=(
    elm-oracle
    elm-format
    neovim
    spaceship-zsh-theme
    apollo
    @elm-tooling/elm-language-server
)

for i in "${packages[@]}"
do
  npm install -g "$i"
done
