#!/bin/zsh

function install_nvm {
  if ! type "nvm"; then
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  fi
}

packages=(
    elm-oracle
    elm-format
    neovim
)

for i in "${packages[@]}"
do
  npm install -g "$i"
done
