# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Theme name see inspiration https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="spaceship"
SPACESHIP_BATTERY_SHOW=false

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh
source "$HOME/.oh-my-zsh/custom/themes/spaceship.zsh-theme"

### TOOLS ###
# Volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# iTerm
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# SSH Agent
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

# Tmux
alias tat="tmux attach -t"
alias tnn="tmux new -s"

# Git
fd() {
  preview="git diff $@ --color=always -- {-1}"
  git diff $@ --name-only | fzf -m --ansi --preview $preview
}

### LANGUAGES ###
# Go
export GO111MODULE=auto
export GOPATH=$HOME/go
export GOPRIVATE=github.com/UrgeToday/*
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH

# Python
alias python="/opt/homebrew/bin/python3"
alias pip3="/opt/homebrew/bin/pip"
export PYTHONPATH="$HOME/scripts:$PYTHONPATH"

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"

### SETTINGS ###
# You may need to manually set your language environment
export LANG=da_DK.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
fi

# Custome aliases
alias icloud="cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs"
alias savemyday="cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/SaveMyDay"
alias "to-urge-docs"="cd ~/Google\ Docs/Urge/"
alias "to-urge-ios"="cd ~/go/src/urge/ios"
alias "to-urge-code"="cd ~/go/src/urge/web-mono"
alias "vim-keys"="cat ~/dotfiles/vim/vimrc"
alias shortcuts="cd ~/dotfiles/shortcuts"
alias "jetbrains-shortcuts"="shortcuts && cat JetbrainsCheatSheat.md"

alias "to-xcode-templates"="cd ~/Library/Developer/Xcode/Templates/"

alias safdef="defaultbrowser safari"
alias firdef="defaultbrowser firefox"
