# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/mathiasegekvist/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="spaceship"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# aliases 
export URGE_DIR="~/Urge/go/src/gitlab.com/URGE/" 
alias urgemain="cd $URGE_DIR/Main"
alias urgeserver="cd $URGE_DIR/Main/server"
alias urgeclient="cd $URGE_DIR/Main/client"
alias urgeinfo="cd $URGE_DIR/Main/information-api"
alias urgeios="cd $URGE_DIR/iOS"

export SaveMyDay_DIR="~/Library/Mobile\ Documents/com\~apple\~CloudDocs/SaveMyDay/"
alias smdweb="cd $SaveMyDay_DIR/Hjemmeside"

export PRIVATE_DIR="~/Google\ Drive/SaveMyDay/Opgaver/Mathias\ Egekvist"
alias gotomathias="cd $PRIVATE_DIR"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$PATH:/opt/yarn-[version]/bin"

export GOPATH=$HOME/Urge/go/
export PATH=$GOPATH/bin:$PATH

export PATH="$PATH:$(brew --prefix)/bin"
export PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
