# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/mathiasegekvist/.oh-my-zsh"

# Theme name see inspiration https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="spaceship"
SPACESHIP_BATTERY_SHOW=false

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
export LANG=da_DK.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
fi

# For a full list of active aliases, run `alias`.
alias iCloud="cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs"
alias savemyday="cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/SaveMyDay"
alias "to-urge-docs"="cd ~/Google\ Docs/Urge/"
alias "to-urge-ios"="cd ~/go/src/Urge/iOS"
alias "to-urge-code"="cd ~/go/src/Urge/Main"
alias "vim-keys"="cat ~/dotfiles/vim/vimrc"
alias shortcuts="cd ~/dotfiles/shortcuts"
alias "jetbrains-shortcuts"="shortcuts && cat JetbrainsCheatSheat.md"

alias "to-xcode-templates"="cd /Users/mathiasegekvist/Library/Developer/Xcode/Templates/"

alias "to-stofa-ios"="cd ~/Projects/ios-webtv"
alias "to-stofa-striber"="cd ~/Projects/stribe-tool"

alias edit="nvim ."
alias vpnconnect="~/scripts/vpnconnect.sh"
alias vpndisconnect='/opt/cisco/anyconnect/bin/vpn disconnect'
alias vpnstatus='/opt/cisco/anyconnect/bin/vpn state'

alias safdef="defaultbrowser safari"
alias firdef="defaultbrowser firefox"

# Go
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


source "/Users/mathiasegekvist/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
export PATH="/usr/local/sbin:$PATH"
