#!/bin/zsh

command -v volta >/dev/null 2>&1 || { 
	echo >&2 "Installing Volta Now"; \
    curl https://get.volta.sh | bash \
    volta install node
}

packages=(
    apollo
    typescript-language-server
    typescript
    diagnostic-languageserver
    eslint_d
    prettier_d_slim
    prettier
)

for i in "${packages[@]}"
do
  npm install -g "$i"
done
